name: Build and Release

on:
  workflow_dispatch:
    inputs:
      node-version:
        description: 'Nodejs Version'
        required: true
        default: '22'
        type: choice
        options:
          - '20'
          - '22'
          - '24'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'

      - name: Install dependent
        run: npm install

      - name: Build project
        run: |
          npm run build
          echo "DATE=$(date +%Y%m%d-%H%M)" >> $GITHUB_ENV

      - name: Packaged build
        run: |
          mv dist pretext-breaker
          tar --zstd -cf dist.tar.zst pretext-breaker/

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.DATE }}
          name: Release ${{ env.DATE }}
          files: dist.tar.zst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
