name: Build and Deploy
run-name: ${{ inputs.run-mode }}

on:
  workflow_dispatch:
    inputs:
      node-version:
        description: 'Nodejs Version'
        required: true
        default: '24'
        type: choice
        options: ['20', '22', '24']
      run-mode:
        description: 'Run Mode'
        required: true
        default: 'Release and Deploy'
        type: choice
        options: ['Only Release', 'Only Deploy', 'Release and Deploy']

permissions:
  contents: write
  pages: write
  id-token: write

#concurrency:
#  group: pages
#  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.date.outputs.DATE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Nodejs
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm

      - name: Install dependent
        run: npm ci

      - name: Build project
        id: date
        run: |
          npm run build
          echo "DATE=$(date +%Y%m%d-%H%M)" >> "$GITHUB_OUTPUT"

      - name: Upload dist artifact
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist/**

      - name: Upload Pages artifact
        if: ${{ inputs.run-mode == 'Only Deploy' || inputs.run-mode == 'Release and Deploy' }}
        uses: actions/upload-pages-artifact@v5
        with:
          path: dist

  release:
    needs: build
    if: ${{ inputs.run-mode == 'Only Release' || inputs.run-mode == 'Release and Deploy' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v8
        with:
          name: dist
          path: pretext-breaker

      - name: Packaged dist
        run: |
          tar --zstd -cf dist.tar.zst pretext-breaker/

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.build.outputs.date }}
          name: Release ${{ needs.build.outputs.date }}
          files: dist.tar.zst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: build
    if: ${{ inputs.run-mode == 'Only Deploy' || inputs.run-mode == 'Release and Deploy' }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
